spring.application.name=LabManagement

spring.data.mongodb.uri=mongodb://localhost:27017/labmanagement
spring.data.mongodb.database=labmanagement

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jinolinjuna@gmail.com
spring.mail.password=gzlbegdoouhfjkxe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true